# Generated by Django 4.2.7 on 2023-11-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlshortener",
            name="short_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
